### ISSUE TITLE
Pistol does not shoot more than once when button is held

### ISSUE THREAD

**Issue by codex41** [DriftWare07/Dungeon-Crawler#1]
Is this intentional? it would be nice if it was on cooldown. just a thought :P

**Comment by DriftWare07** [comment]
Yes, it is intentional. The guns already operate on a cooldown too, didn't consider letting the player hold instead of mash

**Comment by DriftWare07** [comment]
I tried it, and it's a lot more fun with the more rapid-fire guns.
Thanks for the suggestion.
